-- DROP TABLE people IF EXISTS;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE people';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

CREATE TABLE people  (
    person_id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    first_name VARCHAR(20),
    last_name VARCHAR(20)
);